-- VitaCore / PRO Hospital Management System
-- PostgreSQL schema (Neon) — replaces the former MongoDB document store.
--
-- Design notes:
--   * Every entity that used to be a Mongo collection is a real table here,
--     with typed columns for everything the application actually filters,
--     sorts, stores as a number/boolean, or joins on. Column names match the
--     original Mongo document field names exactly (including "_id" as the
--     literal primary key column) so the Python query/serialization layer
--     needs no name-translation logic.
--   * A handful of HMS operational entities (appointments, wards, rooms,
--     beds, lab/radiology orders, pharmacy, invoices, etc.) were served by a
--     single generic Mongo CRUD dispatcher that accepted arbitrary extra
--     fields per record. Those tables keep their well-known/queried columns
--     as real typed columns, plus a "data" JSONB column for the residual
--     free-form fields the dispatcher passes through untouched. Every other
--     table also carries a "data" JSONB catch-all as a safety net.
--   * Fields that were Mongo subdocuments/dicts with dynamic keys (psych
--     session note_detail, daily_report schedule, attendance days, invoice
--     line items/payments, site profile, report layout config) stay as
--     JSONB, matching their original shape 1:1.
--   * All primary keys are TEXT (UUIDv4 strings) generated by the
--     application, matching the previous opaque Mongo ObjectId string.

-- ── Users & Auth ──────────────────────────────────────────────────────────

CREATE TABLE users (
    "_id" TEXT PRIMARY KEY,
    "username" TEXT NOT NULL,
    "password" TEXT,
    "role" TEXT NOT NULL,
    "name" TEXT,
    "email" TEXT,
    "phone" TEXT,
    "is_primary_admin" BOOLEAN NOT NULL DEFAULT FALSE,
    "temp_password_active" BOOLEAN NOT NULL DEFAULT FALSE,
    "day_shift" BOOLEAN NOT NULL DEFAULT FALSE,
    "night_shift" BOOLEAN NOT NULL DEFAULT FALSE,
    "patient_ids" TEXT[] NOT NULL DEFAULT '{}',
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    "updated_at" TIMESTAMPTZ,
    "deleted_at" TIMESTAMPTZ,
    "data" JSONB NOT NULL DEFAULT '{}'::jsonb
);
CREATE UNIQUE INDEX users_username_uidx ON users ("username") WHERE "deleted_at" IS NULL;
CREATE INDEX users_email_idx ON users ("email");

-- ── Patients ──────────────────────────────────────────────────────────────

CREATE TABLE patients (
    "_id" TEXT PRIMARY KEY,
    "name" TEXT,
    "fatherName" TEXT,
    "contactNo" TEXT,
    "cnic" TEXT,
    "guardianPhone" TEXT,
    "guardianName" TEXT,
    "relation" TEXT,
    "address" TEXT,
    "age" TEXT,
    "gender" TEXT,
    "idNo" TEXT,
    "complaint" TEXT,
    "drug" TEXT,
    "drugProblem" TEXT,
    "maritalStatus" TEXT,
    "prevAdmissions" TEXT,
    "admissionDate" TEXT,
    "dischargeDate" TEXT,
    "monthlyFee" TEXT DEFAULT '0',
    "monthlyAllowance" TEXT DEFAULT '3000',
    "receivedAmount" TEXT DEFAULT '0',
    "laundryStatus" BOOLEAN NOT NULL DEFAULT FALSE,
    "laundryAmount" INTEGER NOT NULL DEFAULT 0,
    "photo1" TEXT DEFAULT '',
    "photo2" TEXT DEFAULT '',
    "photo3" TEXT DEFAULT '',
    "isDischarged" BOOLEAN NOT NULL DEFAULT FALSE,
    "notes" JSONB NOT NULL DEFAULT '[]'::jsonb,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    "deleted_at" TIMESTAMPTZ,
    "data" JSONB NOT NULL DEFAULT '{}'::jsonb
);
CREATE INDEX patients_admission_date_idx ON patients ("admissionDate" DESC);
CREATE INDEX patients_is_discharged_idx ON patients ("isDischarged");

CREATE TABLE patient_records (
    "_id" TEXT PRIMARY KEY,
    "patient_id" TEXT NOT NULL,
    "type" TEXT NOT NULL,
    "text" TEXT,
    "title" TEXT,
    "details" TEXT,
    "date" TIMESTAMPTZ NOT NULL DEFAULT now(),
    "recorded_by" TEXT,
    "updated_at" TIMESTAMPTZ,
    "updated_by" TEXT,
    "deleted_at" TIMESTAMPTZ,
    "deleted_by" TEXT,
    "data" JSONB NOT NULL DEFAULT '{}'::jsonb
);
CREATE INDEX patient_records_patient_idx ON patient_records ("patient_id", "date" DESC);

-- ── Finance ───────────────────────────────────────────────────────────────

CREATE TABLE expenses (
    "_id" TEXT PRIMARY KEY,
    "type" TEXT NOT NULL,
    "amount" INTEGER NOT NULL DEFAULT 0,
    "category" TEXT,
    "note" TEXT,
    "payment_method" TEXT,
    "patient_id" TEXT,
    "screenshot" TEXT,
    "date" TIMESTAMPTZ NOT NULL DEFAULT now(),
    "recorded_by" TEXT,
    "auto" BOOLEAN NOT NULL DEFAULT FALSE,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    "updated_at" TIMESTAMPTZ,
    "deleted_at" TIMESTAMPTZ,
    "data" JSONB NOT NULL DEFAULT '{}'::jsonb
);
CREATE INDEX expenses_date_idx ON expenses ("date" DESC);
CREATE INDEX expenses_category_idx ON expenses ("category");
CREATE INDEX expenses_patient_idx ON expenses ("patient_id");
CREATE INDEX expenses_type_category_idx ON expenses ("type", "category");

CREATE TABLE old_balances (
    "_id" TEXT PRIMARY KEY,
    "name" TEXT,
    "amount" INTEGER NOT NULL DEFAULT 0,
    "commitment_date" TEXT,
    "last_call_date" TEXT,
    "note" TEXT,
    "month" INTEGER,
    "year" INTEGER,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    "added_by" TEXT,
    "data" JSONB NOT NULL DEFAULT '{}'::jsonb
);

CREATE TABLE manual_discharge_receipts (
    "_id" TEXT PRIMARY KEY,
    "patient_id" TEXT,
    "patient_name" TEXT,
    "father_name" TEXT,
    "age" TEXT,
    "cnic" TEXT,
    "contact_no" TEXT,
    "area" TEXT,
    "address" TEXT,
    "admission_date" TEXT,
    "discharge_date" TEXT,
    "stay_days" INTEGER NOT NULL DEFAULT 0,
    "monthly_fee" INTEGER NOT NULL DEFAULT 0,
    "fee_amount" INTEGER NOT NULL DEFAULT 0,
    "rehab_next_month_amount" INTEGER NOT NULL DEFAULT 0,
    "test_amount" INTEGER NOT NULL DEFAULT 0,
    "canteen_amount" INTEGER NOT NULL DEFAULT 0,
    "laundry_amount" INTEGER NOT NULL DEFAULT 0,
    "barbar_amount" INTEGER NOT NULL DEFAULT 0,
    "medicine_amount" INTEGER NOT NULL DEFAULT 0,
    "other_amount" INTEGER NOT NULL DEFAULT 0,
    "received_amount" INTEGER NOT NULL DEFAULT 0,
    "net_balance" INTEGER NOT NULL DEFAULT 0,
    "notes" TEXT,
    "created_by" TEXT,
    "updated_by" TEXT,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    "updated_at" TIMESTAMPTZ,
    "data" JSONB NOT NULL DEFAULT '{}'::jsonb
);

-- ── Canteen ───────────────────────────────────────────────────────────────

CREATE TABLE canteen_sales (
    "_id" TEXT PRIMARY KEY,
    "patient_id" TEXT NOT NULL,
    "item" TEXT,
    "amount" INTEGER NOT NULL DEFAULT 0,
    "date" TIMESTAMPTZ NOT NULL DEFAULT now(),
    "entry_type" TEXT,
    "recorded_by" TEXT,
    "edited_by" TEXT,
    "edited_at" TIMESTAMPTZ,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    "deleted_at" TIMESTAMPTZ,
    "data" JSONB NOT NULL DEFAULT '{}'::jsonb
);
CREATE INDEX canteen_sales_patient_idx ON canteen_sales ("patient_id");
CREATE INDEX canteen_sales_date_idx ON canteen_sales ("date" DESC);

CREATE TABLE canteen_balance_overrides (
    "_id" TEXT PRIMARY KEY,
    "patient_id" TEXT NOT NULL,
    "month" INTEGER NOT NULL,
    "year" INTEGER NOT NULL,
    "old_balance" INTEGER NOT NULL DEFAULT 0,
    "updated_at" TIMESTAMPTZ,
    "updated_by" TEXT,
    "data" JSONB NOT NULL DEFAULT '{}'::jsonb,
    UNIQUE ("patient_id", "month", "year")
);

-- ── Staff / HR ────────────────────────────────────────────────────────────

CREATE TABLE employees (
    "_id" TEXT PRIMARY KEY,
    "name" TEXT,
    "designation" TEXT,
    "pay" TEXT,
    "advance" TEXT,
    "advance_month" INTEGER,
    "advance_year" INTEGER,
    "duty_timings" TEXT,
    "date_of_joining" TEXT,
    "cnic" TEXT,
    "phone" TEXT,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    "deleted_at" TIMESTAMPTZ,
    "data" JSONB NOT NULL DEFAULT '{}'::jsonb
);

CREATE TABLE attendance (
    "_id" TEXT PRIMARY KEY,
    "employee_id" TEXT NOT NULL,
    "month" INTEGER NOT NULL,
    "year" INTEGER NOT NULL,
    "days" JSONB NOT NULL DEFAULT '{}'::jsonb,
    UNIQUE ("employee_id", "month", "year")
);

-- ── Overheads / Utilities ─────────────────────────────────────────────────

CREATE TABLE overheads (
    "_id" TEXT PRIMARY KEY,
    "date" TEXT NOT NULL,
    "month" INTEGER NOT NULL,
    "year" INTEGER NOT NULL,
    "kitchen" NUMERIC NOT NULL DEFAULT 0,
    "canteen_auto" NUMERIC NOT NULL DEFAULT 0,
    "others" NUMERIC NOT NULL DEFAULT 0,
    "pay_advance" NUMERIC NOT NULL DEFAULT 0,
    "employee_names" TEXT,
    "income" NUMERIC NOT NULL DEFAULT 0,
    "total_expense" NUMERIC NOT NULL DEFAULT 0,
    "last_updated" TIMESTAMPTZ,
    "data" JSONB NOT NULL DEFAULT '{}'::jsonb,
    UNIQUE ("date", "month", "year")
);
CREATE INDEX overheads_month_year_idx ON overheads ("month", "year");

CREATE TABLE utility_bills (
    "_id" TEXT PRIMARY KEY,
    "type" TEXT,
    "provider" TEXT,
    "amount" INTEGER NOT NULL DEFAULT 0,
    "due_date" TEXT,
    "ref_no" TEXT,
    "status" TEXT DEFAULT 'Unpaid',
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    "deleted_at" TIMESTAMPTZ,
    "data" JSONB NOT NULL DEFAULT '{}'::jsonb
);

-- ── Clinical / Reports ────────────────────────────────────────────────────

CREATE TABLE call_meeting_tracker (
    "_id" TEXT PRIMARY KEY,
    "name" TEXT NOT NULL,
    "day" INTEGER NOT NULL,
    "month" INTEGER NOT NULL,
    "year" INTEGER NOT NULL,
    "type" TEXT,
    "status" TEXT,
    "date_of_admission" TEXT,
    "recorded_by" TEXT,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    "data" JSONB NOT NULL DEFAULT '{}'::jsonb,
    UNIQUE ("name", "day", "month", "year")
);

CREATE TABLE psych_sessions (
    "_id" TEXT PRIMARY KEY,
    "psychologist_id" TEXT,
    "date" TIMESTAMPTZ NOT NULL,
    "time_slot" TEXT,
    "title" TEXT,
    "note" TEXT,
    "note_detail" JSONB,
    "note_author" TEXT,
    "note_at" TIMESTAMPTZ,
    "patient_ids" TEXT[] NOT NULL DEFAULT '{}',
    "created_by" TEXT,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    "updated_by" TEXT,
    "updated_at" TIMESTAMPTZ,
    "data" JSONB NOT NULL DEFAULT '{}'::jsonb
);
CREATE INDEX psych_sessions_date_idx ON psych_sessions ("date");

CREATE TABLE daily_reports (
    "_id" TEXT PRIMARY KEY,
    "patient_id" TEXT NOT NULL,
    "date" TEXT NOT NULL,
    "vitals" TEXT,
    "mood" TEXT,
    "behavior" TEXT,
    "diet_status" TEXT,
    "notes" TEXT,
    "created_by" TEXT,
    "schedule" JSONB NOT NULL DEFAULT '{}'::jsonb,
    "updated_at" TIMESTAMPTZ,
    "updated_by" TEXT,
    "data" JSONB NOT NULL DEFAULT '{}'::jsonb
);
CREATE INDEX daily_reports_patient_idx ON daily_reports ("patient_id", "date" DESC);

CREATE TABLE report_config (
    "_id" TEXT PRIMARY KEY,
    "day_columns" JSONB,
    "night_columns" JSONB
);

CREATE TABLE emergency_alerts (
    "_id" TEXT PRIMARY KEY,
    "patient_name" TEXT,
    "note" TEXT,
    "severity" TEXT DEFAULT 'critical',
    "added_by" TEXT,
    "status" TEXT DEFAULT 'active',
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    "resolved_at" TIMESTAMPTZ,
    "resolved_by" TEXT,
    "data" JSONB NOT NULL DEFAULT '{}'::jsonb
);
CREATE INDEX emergency_alerts_status_idx ON emergency_alerts ("status");

-- ── System / Communications ──────────────────────────────────────────────

CREATE TABLE app_settings (
    "_id" TEXT PRIMARY KEY,
    "key" TEXT NOT NULL,
    "profile" JSONB,
    "updated_at" TIMESTAMPTZ,
    "updated_by" TEXT,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX app_settings_key_uidx ON app_settings ("key");

CREATE TABLE audit_logs (
    "_id" TEXT PRIMARY KEY,
    "timestamp" TIMESTAMPTZ NOT NULL DEFAULT now(),
    "user_id" TEXT,
    "username" TEXT,
    "role" TEXT,
    "method" TEXT,
    "path" TEXT,
    "endpoint" TEXT,
    "status_code" INTEGER,
    "action" TEXT,
    "module" TEXT,
    "document_id" TEXT,
    "ip" TEXT,
    "payload" JSONB
);
CREATE INDEX audit_logs_timestamp_idx ON audit_logs ("timestamp" DESC);

CREATE TABLE whatsapp_logs (
    "_id" TEXT PRIMARY KEY,
    "phone_number" TEXT,
    "message_type" TEXT,
    "payload" JSONB,
    "provider" TEXT,
    "sent_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    "success" BOOLEAN,
    "provider_response" JSONB
);
CREATE INDEX whatsapp_logs_sent_at_idx ON whatsapp_logs ("sent_at" DESC);

CREATE TABLE meetings (
    "_id" TEXT PRIMARY KEY,
    "patient_id" TEXT,
    "patient_name" TEXT,
    "family_user_id" TEXT,
    "family_name" TEXT,
    "type" TEXT,
    "requested_date" TIMESTAMPTZ,
    "status" TEXT DEFAULT 'pending',
    "admin_note" TEXT,
    "confirmed_date" TIMESTAMPTZ,
    "note" TEXT,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    "updated_by" TEXT,
    "updated_at" TIMESTAMPTZ,
    "deleted_at" TIMESTAMPTZ,
    "data" JSONB NOT NULL DEFAULT '{}'::jsonb
);
CREATE INDEX meetings_family_user_idx ON meetings ("family_user_id");

CREATE TABLE hms_counters (
    "_id" TEXT PRIMARY KEY,
    "seq" INTEGER NOT NULL DEFAULT 0,
    "updated_at" TIMESTAMPTZ
);

-- ── HMS generic-entity tables ─────────────────────────────────────────────
-- Each carries the columns the app actually filters/joins on, plus a
-- "data" JSONB catch-all for the remaining free-form fields the generic
-- create/update dispatcher passes through untouched.

CREATE TABLE wards (
    "_id" TEXT PRIMARY KEY,
    "public_id" TEXT,
    "type" TEXT,
    "data" JSONB NOT NULL DEFAULT '{}'::jsonb,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    "updated_at" TIMESTAMPTZ,
    "created_by" TEXT,
    "deleted_at" TIMESTAMPTZ
);

CREATE TABLE rooms (
    "_id" TEXT PRIMARY KEY,
    "public_id" TEXT,
    "ward_id" TEXT,
    "type" TEXT,
    "data" JSONB NOT NULL DEFAULT '{}'::jsonb,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    "updated_at" TIMESTAMPTZ,
    "created_by" TEXT,
    "deleted_at" TIMESTAMPTZ
);

CREATE TABLE beds (
    "_id" TEXT PRIMARY KEY,
    "public_id" TEXT,
    "ward_id" TEXT,
    "room_id" TEXT,
    "status" TEXT DEFAULT 'Available',
    "patient_id" TEXT,
    "data" JSONB NOT NULL DEFAULT '{}'::jsonb,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    "updated_at" TIMESTAMPTZ,
    "created_by" TEXT,
    "deleted_at" TIMESTAMPTZ
);
CREATE INDEX beds_ward_room_status_idx ON beds ("ward_id", "room_id", "status");

CREATE TABLE doctor_schedules (
    "_id" TEXT PRIMARY KEY,
    "public_id" TEXT,
    "doctor_id" TEXT,
    "weekday" TEXT,
    "data" JSONB NOT NULL DEFAULT '{}'::jsonb,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    "updated_at" TIMESTAMPTZ,
    "created_by" TEXT,
    "deleted_at" TIMESTAMPTZ
);

CREATE TABLE appointments (
    "_id" TEXT PRIMARY KEY,
    "public_id" TEXT,
    "appointment_no" TEXT,
    "patient_id" TEXT,
    "doctor_id" TEXT,
    "date" TEXT,
    "status" TEXT DEFAULT 'Waiting',
    "token_number" INTEGER,
    "data" JSONB NOT NULL DEFAULT '{}'::jsonb,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    "updated_at" TIMESTAMPTZ,
    "created_by" TEXT,
    "deleted_at" TIMESTAMPTZ
);
CREATE INDEX appointments_date_status_idx ON appointments ("date", "status");

CREATE TABLE opd_visits (
    "_id" TEXT PRIMARY KEY,
    "public_id" TEXT,
    "visit_no" TEXT,
    "patient_id" TEXT,
    "appointment_id" TEXT,
    "doctor_id" TEXT,
    "date" TEXT,
    "service_name" TEXT,
    "billable_amount" INTEGER NOT NULL DEFAULT 0,
    "invoice_id" TEXT,
    "billed_at" TIMESTAMPTZ,
    "data" JSONB NOT NULL DEFAULT '{}'::jsonb,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    "updated_at" TIMESTAMPTZ,
    "created_by" TEXT,
    "deleted_at" TIMESTAMPTZ
);
CREATE INDEX opd_visits_patient_date_idx ON opd_visits ("patient_id", "date" DESC);

CREATE TABLE ipd_admissions (
    "_id" TEXT PRIMARY KEY,
    "public_id" TEXT,
    "ipd_no" TEXT,
    "patient_id" TEXT,
    "status" TEXT DEFAULT 'Admitted',
    "bed_id" TEXT,
    "admission_date" TEXT,
    "discharge_date" TEXT,
    "room_rate" INTEGER NOT NULL DEFAULT 0,
    "admission_charge" INTEGER NOT NULL DEFAULT 0,
    "room_charged_until" TEXT,
    "admission_invoice_id" TEXT,
    "last_room_invoice_id" TEXT,
    "last_room_billed_at" TIMESTAMPTZ,
    "data" JSONB NOT NULL DEFAULT '{}'::jsonb,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    "updated_at" TIMESTAMPTZ,
    "created_by" TEXT,
    "deleted_at" TIMESTAMPTZ
);
CREATE INDEX ipd_admissions_patient_status_idx ON ipd_admissions ("patient_id", "status");

CREATE TABLE bed_transfers (
    "_id" TEXT PRIMARY KEY,
    "public_id" TEXT,
    "patient_id" TEXT,
    "admission_id" TEXT,
    "from_bed_id" TEXT,
    "to_bed_id" TEXT,
    "transfer_date" TEXT,
    "data" JSONB NOT NULL DEFAULT '{}'::jsonb,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    "updated_at" TIMESTAMPTZ,
    "created_by" TEXT,
    "deleted_at" TIMESTAMPTZ
);

CREATE TABLE vitals (
    "_id" TEXT PRIMARY KEY,
    "public_id" TEXT,
    "patient_id" TEXT,
    "date" TEXT,
    "data" JSONB NOT NULL DEFAULT '{}'::jsonb,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    "updated_at" TIMESTAMPTZ,
    "created_by" TEXT,
    "deleted_at" TIMESTAMPTZ
);
CREATE INDEX vitals_patient_idx ON vitals ("patient_id", "created_at" DESC);

CREATE TABLE nursing_notes (
    "_id" TEXT PRIMARY KEY,
    "public_id" TEXT,
    "patient_id" TEXT,
    "date" TEXT,
    "data" JSONB NOT NULL DEFAULT '{}'::jsonb,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    "updated_at" TIMESTAMPTZ,
    "created_by" TEXT,
    "deleted_at" TIMESTAMPTZ
);
CREATE INDEX nursing_notes_patient_idx ON nursing_notes ("patient_id", "created_at" DESC);

CREATE TABLE medication_administration (
    "_id" TEXT PRIMARY KEY,
    "public_id" TEXT,
    "patient_id" TEXT,
    "date" TEXT,
    "data" JSONB NOT NULL DEFAULT '{}'::jsonb,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    "updated_at" TIMESTAMPTZ,
    "created_by" TEXT,
    "deleted_at" TIMESTAMPTZ
);
CREATE INDEX medication_administration_patient_idx ON medication_administration ("patient_id", "created_at" DESC);

CREATE TABLE lab_tests (
    "_id" TEXT PRIMARY KEY,
    "public_id" TEXT,
    "category" TEXT,
    "name" TEXT,
    "price" INTEGER NOT NULL DEFAULT 0,
    "data" JSONB NOT NULL DEFAULT '{}'::jsonb,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    "updated_at" TIMESTAMPTZ,
    "created_by" TEXT,
    "deleted_at" TIMESTAMPTZ
);
CREATE INDEX lab_tests_name_idx ON lab_tests ("name");

CREATE TABLE lab_orders (
    "_id" TEXT PRIMARY KEY,
    "public_id" TEXT,
    "patient_id" TEXT,
    "test_id" TEXT,
    "test_name" TEXT,
    "billable_amount" INTEGER NOT NULL DEFAULT 0,
    "status" TEXT DEFAULT 'Ordered',
    "order_date" TEXT,
    "source" TEXT,
    "invoice_id" TEXT,
    "billed_at" TIMESTAMPTZ,
    "data" JSONB NOT NULL DEFAULT '{}'::jsonb,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    "updated_at" TIMESTAMPTZ,
    "created_by" TEXT,
    "deleted_at" TIMESTAMPTZ
);
CREATE INDEX lab_orders_patient_status_idx ON lab_orders ("patient_id", "status");

CREATE TABLE radiology_orders (
    "_id" TEXT PRIMARY KEY,
    "public_id" TEXT,
    "patient_id" TEXT,
    "study_name" TEXT,
    "modality" TEXT,
    "billable_amount" INTEGER NOT NULL DEFAULT 0,
    "status" TEXT DEFAULT 'Ordered',
    "order_date" TEXT,
    "invoice_id" TEXT,
    "billed_at" TIMESTAMPTZ,
    "report_text" TEXT,
    "data" JSONB NOT NULL DEFAULT '{}'::jsonb,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    "updated_at" TIMESTAMPTZ,
    "created_by" TEXT,
    "deleted_at" TIMESTAMPTZ
);
CREATE INDEX radiology_orders_patient_status_idx ON radiology_orders ("patient_id", "status");

CREATE TABLE radiology_reports (
    "_id" TEXT PRIMARY KEY,
    "public_id" TEXT,
    "patient_id" TEXT,
    "order_id" TEXT,
    "report_text" TEXT,
    "data" JSONB NOT NULL DEFAULT '{}'::jsonb,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    "updated_at" TIMESTAMPTZ,
    "created_by" TEXT,
    "deleted_at" TIMESTAMPTZ
);

CREATE TABLE pharmacy_items (
    "_id" TEXT PRIMARY KEY,
    "public_id" TEXT,
    "name" TEXT,
    "category" TEXT,
    "stock" INTEGER NOT NULL DEFAULT 0,
    "purchase_price" INTEGER NOT NULL DEFAULT 0,
    "sale_price" INTEGER NOT NULL DEFAULT 0,
    "data" JSONB NOT NULL DEFAULT '{}'::jsonb,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    "updated_at" TIMESTAMPTZ,
    "created_by" TEXT,
    "deleted_at" TIMESTAMPTZ
);
CREATE INDEX pharmacy_items_name_idx ON pharmacy_items ("name");

CREATE TABLE pharmacy_batches (
    "_id" TEXT PRIMARY KEY,
    "public_id" TEXT,
    "medicine_id" TEXT,
    "quantity" INTEGER NOT NULL DEFAULT 0,
    "remaining" INTEGER NOT NULL DEFAULT 0,
    "data" JSONB NOT NULL DEFAULT '{}'::jsonb,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    "updated_at" TIMESTAMPTZ,
    "created_by" TEXT,
    "deleted_at" TIMESTAMPTZ
);
CREATE INDEX pharmacy_batches_medicine_idx ON pharmacy_batches ("medicine_id");

CREATE TABLE pharmacy_dispenses (
    "_id" TEXT PRIMARY KEY,
    "public_id" TEXT,
    "patient_id" TEXT,
    "medicine_id" TEXT,
    "batch_id" TEXT,
    "quantity" INTEGER NOT NULL DEFAULT 0,
    "sale_price" INTEGER NOT NULL DEFAULT 0,
    "medicine_name" TEXT,
    "billable_amount" INTEGER NOT NULL DEFAULT 0,
    "invoice_id" TEXT,
    "billed_at" TIMESTAMPTZ,
    "date" TEXT,
    "data" JSONB NOT NULL DEFAULT '{}'::jsonb,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    "updated_at" TIMESTAMPTZ,
    "created_by" TEXT,
    "deleted_at" TIMESTAMPTZ
);
CREATE INDEX pharmacy_dispenses_patient_idx ON pharmacy_dispenses ("patient_id", "date" DESC);

CREATE TABLE stock_ledger (
    "_id" TEXT PRIMARY KEY,
    "public_id" TEXT,
    "medicine_id" TEXT,
    "batch_id" TEXT,
    "patient_id" TEXT,
    "transaction_type" TEXT,
    "quantity" INTEGER NOT NULL DEFAULT 0,
    "date" TEXT,
    "data" JSONB NOT NULL DEFAULT '{}'::jsonb,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    "updated_at" TIMESTAMPTZ,
    "created_by" TEXT,
    "deleted_at" TIMESTAMPTZ
);
CREATE INDEX stock_ledger_medicine_date_idx ON stock_ledger ("medicine_id", "date" DESC);

CREATE TABLE services (
    "_id" TEXT PRIMARY KEY,
    "public_id" TEXT,
    "category" TEXT,
    "name" TEXT,
    "price" INTEGER NOT NULL DEFAULT 0,
    "data" JSONB NOT NULL DEFAULT '{}'::jsonb,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    "updated_at" TIMESTAMPTZ,
    "created_by" TEXT,
    "deleted_at" TIMESTAMPTZ
);

CREATE TABLE invoices (
    "_id" TEXT PRIMARY KEY,
    "public_id" TEXT,
    "invoice_no" TEXT,
    "patient_id" TEXT,
    "date" TEXT,
    "source" TEXT,
    "subtotal" INTEGER NOT NULL DEFAULT 0,
    "discount_amount" INTEGER NOT NULL DEFAULT 0,
    "total" INTEGER NOT NULL DEFAULT 0,
    "paid_amount" INTEGER NOT NULL DEFAULT 0,
    "refunded_amount" INTEGER NOT NULL DEFAULT 0,
    "status" TEXT DEFAULT 'Unpaid',
    "lines" JSONB NOT NULL DEFAULT '[]'::jsonb,
    "payments" JSONB NOT NULL DEFAULT '[]'::jsonb,
    "source_refs" JSONB NOT NULL DEFAULT '[]'::jsonb,
    "data" JSONB NOT NULL DEFAULT '{}'::jsonb,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    "updated_at" TIMESTAMPTZ,
    "created_by" TEXT,
    "deleted_at" TIMESTAMPTZ
);
CREATE INDEX invoices_patient_status_idx ON invoices ("patient_id", "status");

CREATE TABLE refunds (
    "_id" TEXT PRIMARY KEY,
    "public_id" TEXT,
    "patient_id" TEXT,
    "invoice_id" TEXT,
    "amount" INTEGER NOT NULL DEFAULT 0,
    "status" TEXT DEFAULT 'Approved',
    "date" TEXT,
    "data" JSONB NOT NULL DEFAULT '{}'::jsonb,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    "updated_at" TIMESTAMPTZ,
    "created_by" TEXT,
    "deleted_at" TIMESTAMPTZ
);

CREATE TABLE cash_closings (
    "_id" TEXT PRIMARY KEY,
    "public_id" TEXT,
    "date" TEXT,
    "closed_by" TEXT,
    "cash_total" INTEGER NOT NULL DEFAULT 0,
    "card_total" INTEGER NOT NULL DEFAULT 0,
    "online_total" INTEGER NOT NULL DEFAULT 0,
    "expense_total" INTEGER NOT NULL DEFAULT 0,
    "net_total" INTEGER NOT NULL DEFAULT 0,
    "data" JSONB NOT NULL DEFAULT '{}'::jsonb,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    "updated_at" TIMESTAMPTZ,
    "created_by" TEXT,
    "deleted_at" TIMESTAMPTZ
);
CREATE INDEX cash_closings_date_idx ON cash_closings ("date" DESC);

CREATE TABLE payment_records (
    "_id" TEXT PRIMARY KEY,
    "invoice_id" TEXT,
    "patient_id" TEXT,
    "amount" INTEGER NOT NULL DEFAULT 0,
    "method" TEXT,
    "date" TEXT,
    "source" TEXT,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT now()
);
